# Backup of full integrity workflow prior to minimal debug reduction
name: config-integrity
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  integrity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run integrity & hygiene tests
        run: pytest -q tests/test_config_integrity.py
      - name: Show trigger file
        if: always()
        run: |
          if [ -f deployment-trigger.json ]; then cat deployment-trigger.json; else echo 'No trigger file'; fi
