name: housekeeping-maintenance
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prune backups
        run: |
          python scripts/prune_backups.py || echo "prune_backups.py failed"
      - name: Consolidate logs
        run: |
          python scripts/consolidate_logs.py || echo "consolidate_logs.py failed"
      - name: Show summary artifacts
        if: always()
        run: |
          if [ -f logs/summary_status.json ]; then cat logs/summary_status.json; else echo 'No summary file'; fi
      - name: Dedupe / seed tests
        run: pytest -q tests/test_trigger_dedupe_and_seed.py
