# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Deploy Trading Dashboard

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permissions required by GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    name: Build static site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify static site assets
        run: |
          ls -al public || { echo 'public directory missing'; exit 1; }
          test -f public/index.html || { echo 'public/index.html missing'; exit 1; }
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

