name: Deploy Trading Dashboard

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Required for new Pages deployment model
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # No build step required: static files already in public/
      - name: Verify static site
        run: |
          ls -al public || { echo 'public directory missing'; exit 1; }
          test -f public/index.html || { echo 'public/index.html missing'; exit 1; }
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
