﻿# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: secrets-verification
on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: secrets-verification
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Export & report secrets (single reference)
        shell: bash
        env:
          BOT_SECRET_SRC: ${{ secrets.BOT_SECRET }}
          VERCEL_URL_SRC: ${{ secrets.VERCEL_URL }}
          BINANCE_API_KEY_SRC: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET_SRC: ${{ secrets.BINANCE_API_SECRET }}
        run: |
          set -euo pipefail
          echo 'Checking required secrets (lengths only):'
          missing=0
          for base in BOT_SECRET VERCEL_URL BINANCE_API_KEY BINANCE_API_SECRET; do
            src="${base}_SRC"; val="${!src:-}"
            if [ -n "$val" ]; then
              echo "$base=$val" >> "$GITHUB_ENV"
              echo "[OK] $base len=${#val}"
            else
              echo "[MISSING] $base"; missing=1
            fi
          done
          if [ "$missing" -eq 1 ]; then echo 'One or more required secrets missing' >&2; exit 1; fi
      - name: Live bot endpoint (optional)
        shell: bash
        run: |
          if [ -z "${VERCEL_URL}" ] || [ -z "${BOT_SECRET}" ]; then
            echo 'Skipping live-bot call (missing VERCEL_URL or BOT_SECRET)'; exit 0; fi
          echo 'Calling live-bot endpoint...'
          code=$(curl -s -o /dev/null -w '%{http_code}' -H "x-bot-secret: ${BOT_SECRET}" "${VERCEL_URL%/}/api/live-bot") || true
          echo "HTTP status: $code"
          if [ "$code" != 200 ] && [ "$code" != 401 ]; then
            echo "Unexpected status $code" >&2; exit 1; fi
