name: secrets-health

on:
  schedule:
    - cron: '15 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: secrets-health
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Report required secrets
        shell: bash
        env:
          BOT_SECRET: ${{ secrets.BOT_SECRET }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        run: |
          set -euo pipefail
          missing=0
          for key in BOT_SECRET VERCEL_URL BINANCE_API_KEY BINANCE_API_SECRET; do
            val="${!key:-}"
            if [ -n "$val" ]; then
              echo "[OK] $key len=${#val}"; echo "$key=$val" >> "$GITHUB_ENV"
            else
              echo "[MISSING] $key"; missing=1
            fi
          done
          if [ "$missing" -eq 1 ]; then echo 'One or more required secrets missing' >&2; exit 1; fi
      - name: Optional live-bot probe
        shell: bash
        run: |
          if [ -z "${VERCEL_URL}" ] || [ -z "${BOT_SECRET}" ]; then
            echo 'Skipping live-bot probe'; exit 0; fi
          code=$(curl -s -o /dev/null -w '%{http_code}' -H "x-bot-secret: ${BOT_SECRET}" "${VERCEL_URL%/}/api/live-bot") || true
          echo "HTTP status: $code"
          if [ "$code" != 200 ] && [ "$code" != 401 ]; then
            echo "Unexpected status $code" >&2; exit 1; fi
