name: secrets-verification

on:
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: secrets-verification
  cancel-in-progress: true

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BOT_SECRET: ${{ secrets.BOT_SECRET }}
      VERCEL_URL: ${{ secrets.VERCEL_URL }}
      BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Report presence (masked)
        shell: bash
        run: |
          set -euo pipefail
          missing=()
          check() {
            local name="$1"; local val="${!1:-}";
            if [ -z "$val" ]; then
              missing+=("$name")
              echo "[MISSING] $name"
            else
              echo "[OK] $name length=${#val}"
            fi
          }
          for var in BOT_SECRET VERCEL_URL BINANCE_API_KEY BINANCE_API_SECRET TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID; do
            check "$var"
          done
          if [ ${#missing[@]} -gt 0 ]; then
            echo "Missing secrets: ${missing[*]}" >&2
            exit 1
          fi
      - name: Test Vercel endpoint (unauthenticated dashboard)
        if: env.VERCEL_URL != ''
        shell: bash
        run: |
          set -e
          code=$(curl -s -o /dev/null -w "%{http_code}" "${VERCEL_URL}/api/live-bot") || code=$?
          echo "Dashboard GET /api/live-bot HTTP $code"
      - name: Test Vercel authenticated trading endpoint
        if: env.VERCEL_URL != '' && env.BOT_SECRET != ''
        shell: bash
        run: |
          set -e
          resp=$(curl -s -w "\n%{http_code}" -H "Authorization: Bearer ${BOT_SECRET}" "${VERCEL_URL}/api/live-bot") || true
          body="$(echo "$resp" | head -n -1)"; code="$(echo "$resp" | tail -n1)"
          echo "Authenticated request HTTP $code"
          if [ "$code" != "200" ]; then
            echo "Non-200 authenticated response (code=$code); body snippet:" >&2
            echo "$body" | head -n 20 >&2
          fi
          true
