name: automated-trading-bot

on:
  workflow_dispatch: {}
  schedule:
    # Runs at the top of every hour; adjust as needed. Keep frequency modest to avoid hitting rate limits.
    - cron: '0 * * * *'

permissions:
  contents: read

concurrency:
  group: trading-bot
  cancel-in-progress: true

jobs:
  trading-cycle:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Execute trading cycle (skips if secret missing)
        shell: bash
        env:
          BOT_SECRET: ${{ secrets.BOT_SECRET }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          set -euo pipefail
          # Fallback for VERCEL_URL if not provided as secret
          if [[ -z "${VERCEL_URL:-}" ]]; then
            VERCEL_URL="https://my-trading-robot-1.vercel.app"
          fi
          if [[ -z "${BOT_SECRET:-}" ]]; then
            echo "BOT_SECRET not set in secrets; skipping run safely.";
            exit 0
          fi
          echo "Invoking live bot endpoint at ${VERCEL_URL} (masked auth)..."
          curl -sS -X GET "${VERCEL_URL}/api/live-bot" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${BOT_SECRET}" \
            --max-time 40 --retry 3 --retry-delay 5 --fail
          echo "Trading cycle completed at $(date -u)"
