name: automated-trading-bot

on:
  workflow_dispatch: {}
  schedule:
    # Runs at the top of every hour; adjust as needed. Keep frequency modest to avoid hitting rate limits.
    - cron: '0 * * * *'

permissions:
  contents: read

concurrency:
  group: trading-bot
  cancel-in-progress: true

jobs:
  trading-cycle:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Call live-bot endpoint (skips if secret missing)
        uses: ./.github/actions/call-live-bot
        with:
          vercel-url: ${{ secrets.VERCEL_URL }}
          bot-secret: ${{ secrets.BOT_SECRET }}
          path: /api/live-bot
          method: GET
          fail-on-non-200: true
      - name: Trading cycle timestamp
        run: echo "Trading cycle completed at $(date -u)"
