# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Automated Trading Bot

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: trading-bot
  cancel-in-progress: true

jobs:
  trading-cycle:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Export required secrets
        shell: bash
        env:
          BOT_SECRET_SRC: ${{ secrets.BOT_SECRET }}
          VERCEL_URL_SRC: ${{ secrets.VERCEL_URL }}
        run: |
          set -euo pipefail
          if [ -z "${BOT_SECRET_SRC}" ] || [ -z "${VERCEL_URL_SRC}" ]; then
            echo "[WARN] Missing one or more required secrets (BOT_SECRET / VERCEL_URL)." >&2
            exit 1
          fi
          echo "BOT_SECRET=${BOT_SECRET_SRC}" >> "$GITHUB_ENV"
          echo "VERCEL_URL=${VERCEL_URL_SRC}" >> "$GITHUB_ENV"
          echo "Secrets exported (values masked)."
      - name: Execute Trading Cycle
        shell: bash
        run: |
          set -euo pipefail
          URL="${VERCEL_URL%/}/api/live-bot"
          echo "Calling $URL"
          RESP=$(curl -sS -H "Authorization: Bearer $BOT_SECRET" \
                        -H "Content-Type: application/json" \
                        --retry 3 --retry-delay 5 --max-time 30 \
                        -w "\n%{http_code}" "$URL" || true)
          BODY="$(echo "$RESP" | head -n -1 | head -c 200 | tr '\n' ' ')"
          CODE="$(echo "$RESP" | tail -n1)"
          echo "HTTP $CODE body(snippet)=$BODY"
          if [ "$CODE" != 200 ]; then
            echo "Live bot returned non-200 ($CODE)" >&2; exit 1; fi
      - name: Log Result
        run: echo "Trading cycle completed at $(date -u)"
